// Code generated by Kitex v0.12.0. DO NOT EDIT.

package taskservice

import (
	task "DDD/go-ddd-demo/go-task/kitex_gen/example/go/task"
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	GetTask(ctx context.Context, req *task.GetTaskReq, callOptions ...callopt.Option) (r *task.GetTaskResp, err error)
	CreateTask(ctx context.Context, req *task.CreateTaskReq, callOptions ...callopt.Option) (r *task.CreateTaskResp, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfoForClient(), options...)
	if err != nil {
		return nil, err
	}
	return &kTaskServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kTaskServiceClient struct {
	*kClient
}

func (p *kTaskServiceClient) GetTask(ctx context.Context, req *task.GetTaskReq, callOptions ...callopt.Option) (r *task.GetTaskResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetTask(ctx, req)
}

func (p *kTaskServiceClient) CreateTask(ctx context.Context, req *task.CreateTaskReq, callOptions ...callopt.Option) (r *task.CreateTaskResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CreateTask(ctx, req)
}
