// Code generated by Kitex v0.12.0. DO NOT EDIT.

package taskservice

import (
	task "DDD/go-ddd-demo/go-task/kitex_gen/example/go/task"
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"GetTask": kitex.NewMethodInfo(
		getTaskHandler,
		newTaskServiceGetTaskArgs,
		newTaskServiceGetTaskResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"CreateTask": kitex.NewMethodInfo(
		createTaskHandler,
		newTaskServiceCreateTaskArgs,
		newTaskServiceCreateTaskResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	taskServiceServiceInfo                = NewServiceInfo()
	taskServiceServiceInfoForClient       = NewServiceInfoForClient()
	taskServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return taskServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return taskServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return taskServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "TaskService"
	handlerType := (*task.TaskService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "task",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.12.0",
		Extra:           extra,
	}
	return svcInfo
}

func getTaskHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*task.TaskServiceGetTaskArgs)
	realResult := result.(*task.TaskServiceGetTaskResult)
	success, err := handler.(task.TaskService).GetTask(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newTaskServiceGetTaskArgs() interface{} {
	return task.NewTaskServiceGetTaskArgs()
}

func newTaskServiceGetTaskResult() interface{} {
	return task.NewTaskServiceGetTaskResult()
}

func createTaskHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*task.TaskServiceCreateTaskArgs)
	realResult := result.(*task.TaskServiceCreateTaskResult)
	success, err := handler.(task.TaskService).CreateTask(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newTaskServiceCreateTaskArgs() interface{} {
	return task.NewTaskServiceCreateTaskArgs()
}

func newTaskServiceCreateTaskResult() interface{} {
	return task.NewTaskServiceCreateTaskResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) GetTask(ctx context.Context, req *task.GetTaskReq) (r *task.GetTaskResp, err error) {
	var _args task.TaskServiceGetTaskArgs
	_args.Req = req
	var _result task.TaskServiceGetTaskResult
	if err = p.c.Call(ctx, "GetTask", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) CreateTask(ctx context.Context, req *task.CreateTaskReq) (r *task.CreateTaskResp, err error) {
	var _args task.TaskServiceCreateTaskArgs
	_args.Req = req
	var _result task.TaskServiceCreateTaskResult
	if err = p.c.Call(ctx, "CreateTask", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
