// Code generated by Kitex v0.12.0. DO NOT EDIT.

package ecomservice

import (
	ecom "DDD/go-ddd-demo/go-ecom/kitex_gen/example/go/ecom"
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"GetTask": kitex.NewMethodInfo(
		getTaskHandler,
		newEcomServiceGetTaskArgs,
		newEcomServiceGetTaskResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"CreateTask": kitex.NewMethodInfo(
		createTaskHandler,
		newEcomServiceCreateTaskArgs,
		newEcomServiceCreateTaskResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	ecomServiceServiceInfo                = NewServiceInfo()
	ecomServiceServiceInfoForClient       = NewServiceInfoForClient()
	ecomServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return ecomServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return ecomServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return ecomServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "EcomService"
	handlerType := (*ecom.EcomService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "ecom",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.12.0",
		Extra:           extra,
	}
	return svcInfo
}

func getTaskHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*ecom.EcomServiceGetTaskArgs)
	realResult := result.(*ecom.EcomServiceGetTaskResult)
	success, err := handler.(ecom.EcomService).GetTask(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newEcomServiceGetTaskArgs() interface{} {
	return ecom.NewEcomServiceGetTaskArgs()
}

func newEcomServiceGetTaskResult() interface{} {
	return ecom.NewEcomServiceGetTaskResult()
}

func createTaskHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*ecom.EcomServiceCreateTaskArgs)
	realResult := result.(*ecom.EcomServiceCreateTaskResult)
	success, err := handler.(ecom.EcomService).CreateTask(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newEcomServiceCreateTaskArgs() interface{} {
	return ecom.NewEcomServiceCreateTaskArgs()
}

func newEcomServiceCreateTaskResult() interface{} {
	return ecom.NewEcomServiceCreateTaskResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) GetTask(ctx context.Context, req *ecom.GetTaskReq) (r *ecom.GetTaskResp, err error) {
	var _args ecom.EcomServiceGetTaskArgs
	_args.Req = req
	var _result ecom.EcomServiceGetTaskResult
	if err = p.c.Call(ctx, "GetTask", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) CreateTask(ctx context.Context, req *ecom.CreateTaskReq) (r *ecom.CreateTaskResp, err error) {
	var _args ecom.EcomServiceCreateTaskArgs
	_args.Req = req
	var _result ecom.EcomServiceCreateTaskResult
	if err = p.c.Call(ctx, "CreateTask", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
